%YAML 1.1
---
name: audio-recorder
version: replaced-by-version-script
version-script: |
  set -eu

  cd parts/audio-recorder/src
  upstream_version="$(
    grep PACKAGE_VERSION src/config.h \
      | cut --delimiter=' ' --field=3 \
      | tr --delete '"'
  )"

  upstream_dirtiness=''
  if \
    test \
    "$(
      bzr version-info \
        --custom \
        --template={clean}
    )" \
    -eq \
    0; then
    upstream_dirtiness=-dirty
  fi
  upstream_revision="$(
    bzr version-info \
      --custom \
      --template={revno}
  )"
  cd ../../..

  packaging_revision="$(
    git \
      describe \
      --abbrev=4 \
      --always \
      --dirty=-d
  )"

  printf -- '%s' "${upstream_version}+rev${upstream_revision}${upstream_dirtiness}+pkg-${packaging_revision}"

summary: A free audio-recorder for Linux
description: |
  This amazing program allows you to record your favourite music or audio to a file.
  It can record audio from your system's soundcard, microphones, browsers, webcams & more.
  Put simply; if it plays out of your loudspeakers you can record it.

  It has an advanced timer that can:
  * Start, stop or pause recording at a given clock time.
  * Start, stop or pause after a time period.
  * Stop when the recorded file size exceeds a limit.
  * Start recording on voice or sound (user can set the audio threshold and delay).
  * Stop or pause recording on "silence" (user can set the audio threshold and delay).

  The recording can be atomatically controlled by:
  * RhytmBox audio player.
  * Banshee audio player.
  * Amarok, VLC, Audacious and other MPRIS2 compatible players.
  * Skype. It can automatically record all your Skype calls without any user interaction.

  This program supports several audio (output) formats such as OGG audio, Flac, MP3 and WAV.

  User can also control the recorder from command line with --command <arg> option.
  See audio-recorder --help for more information.

  INFORMATION REGARDING TO SECURITY CONFINEMENT

  Connect to the `removable-media` slot to allow saving recording to removable storages:

    sudo snap connect audio-recorder:removable-media

  NOTE: This is NOT an upstream release and is currently maintained by 林博仁(Buo-ren, Lin), refer to the following issue tracker if you encounter any problem when using this snap:
  https://github.com/Lin-Buo-Ren/audio-recorder-snap/issues
icon: snap/gui/audio-recorder.svg
grade: stable
confinement: strict

plugs:
# graphical resources access
  desktop:
  desktop-legacy:
  x11:
  unity7:

# storage access
  home:
  removable-media:

# audio access
  pulseaudio:

# unknown
  gsettings:
  #mount-observe:
  mpris:

# FIXME: Required by v4l2 plugin of Gstreamer, should be dropped.
  hardware-observe:

#slots:
  # dbus access
  #dbus-service:

  # FIXME: Doesn't appear to work, interface not shown in D-feet
  #dbus-service:
    #interface: dbus
    #name: org.gnome.API.AudioRecorderInterface
    #bus: session

parts:
  # Patches to fix other parts
  patches:
    source: snap/patches
    source-type: local
    plugin: dump

    # DISABLED: Bug #1775582 “`organize:{ /: another-dir/ }` causes the items under host root directory to be copied in another-dir” : Bugs : Snapcraft
    # https://forum.snapcraft.io/t/organize-another-dir-causes-the-items-under-host-root-directory-to-be-copied-in-another-dir/5806
    #organize:
        #/: patches/
    override-build: |
      set -eu

      snapcraftctl build

      mkdir \
        --parents \
        "$SNAPCRAFT_PART_INSTALL"/patches
      mv \
        "$SNAPCRAFT_PART_INSTALL"/*.diff \
        "$SNAPCRAFT_PART_INSTALL"/*.patch \
        "$SNAPCRAFT_PART_INSTALL"/*.sed \
        "$SNAPCRAFT_PART_INSTALL"/patches \
        || true # Empty patches folder is allowed
    stage:
    - patches/*
    override-prime: 'true'

  # Enable ccache by setting up a dependency of this part
  # and prepend /usr/lib/ccache to the PATH colon-
  # separated array:
  #
  #   PATH=/usr/lib/ccache:"${PATH}"
  #
  # NOTE: Currently the above setup can't be applied to
  #       scriptlets as plugins doesn't honor env. var.
  #       customizations.
  #
  # or passing custom CC CXX definition to the parts'
  # configure program.
  ccache:
    plugin: nil
    build-packages:
    - ccache
    # WORKAROUND: Non-snapcraft-generated files are pulled when nil plugin is used - snapcraft - snapcraft.io
    # https://forum.snapcraft.io/t/non-snapcraft-generated-files-are-pulled-when-nil-plugin-is-used/5913
    override-pull: 'true'
    override-build: 'true'
    override-stage: |
      set -eu

      mkdir \
        --parents \
        "${SNAPCRAFT_STAGE}"/build-tools/bin
      ln \
        --force \
        --symbolic \
        "$(which ccache)" \
        "${SNAPCRAFT_STAGE}"/build-tools/bin/gcc
      ln \
        --force \
        --symbolic \
        "$(which ccache)" \
        "${SNAPCRAFT_STAGE}"/build-tools/bin/g++

  audio-recorder:
    after:
    - ccache
    - desktop-gtk3
    - patches

    source: lp:audio-recorder
    override-pull: |
      set -eu

      bzr checkout \
        --lightweight \
        lp:audio-recorder \
        .

    plugin: autotools
    configflags:
    - --datarootdir=/snap/audio-recorder/current/share
    - CC=ccache gcc
    - CXX=ccache g++
    build-packages:
    - gcc
    - intltool
    - libappindicator3-dev
    - libc6-dev
    - libglib2.0-dev
    - libgstreamer1.0-dev
    - libgstreamer-plugins-base1.0-dev
    - libgtk-3-dev
    - pkg-config
    stage-packages:
    - gstreamer1.0-libav
    - gstreamer1.0-plugins-base
    - gstreamer1.0-plugins-good
    - gstreamer1.0-plugins-ugly
    - gstreamer1.0-pulseaudio
    - libappindicator3-1
    - libglib2.0-0
    - libgstreamer1.0-0
    - libgstreamer-plugins-base1.0-0
    - libgtk-3-0

    # From automigration
    - libdb5.3
    - libgl1-mesa-glx
    - libglu1-mesa
    - libgpm2
    - libxcb-glx0
    - libxxf86vm1
    organize:
      snap/audio-recorder/current/: /
    filesets:
      app-resources:
      - share/audio-recorder/*
      cleanup-debris-from-organizing:
      - -snap/*
      executables:
      - bin/*
      desktop-entries:
      - share/applications/*
      files-from-staging-packages:
      - usr/*
      glib-schemas:
      - share/glib-2.0/schemas/*
      icons:
      - share/icons/*
      localization:
      - share/locale/*
      manpages:
      - share/man/*
      pixmaps:
      - share/pixmaps/*
    stage:
    - $cleanup-debris-from-organizing
    override-stage: |
      set -eu

      snapcraftctl stage

      sed \
        --file "${SNAPCRAFT_STAGE}"/patches/postprocess-desktop-entries.sed \
        --in-place \
        "${SNAPCRAFT_STAGE}"/share/applications/*.desktop

apps:
  audio-recorder:
    command: >
      desktop-launch
      audio-recorder
    desktop: share/applications/audio-recorder.desktop
