%YAML 1.1
---
name: audio-recorder
summary: A free audio-recorder for Linux
description: |
  This amazing program allows you to record your favourite music or audio to a file.
  It can record audio from your system's soundcard, microphones, browsers, webcams & more.
  Put simply; if it plays out of your loudspeakers you can record it.

  It has an advanced timer that can:
  * Start, stop or pause recording at a given clock time.
  * Start, stop or pause after a time period.
  * Stop when the recorded file size exceeds a limit.
  * Start recording on voice or sound (user can set the audio threshold and delay).
  * Stop or pause recording on "silence" (user can set the audio threshold and delay).

  The recording can be atomatically controlled by:
  * RhytmBox audio player.
  * Banshee audio player.
  * Amarok, VLC, Audacious and other MPRIS2 compatible players.
  * Skype. It can automatically record all your Skype calls without any user interaction.

  This program supports several audio (output) formats such as OGG audio, Flac, MP3 and WAV.

  User can also control the recorder from command line with --command <arg> option.
  See audio-recorder --help for more information.

  INFORMATION REGARDING TO SECURITY CONFINEMENT

  Connect to the `removable-media` slot to allow saving recording to removable storages:

    sudo snap connect audio-recorder:removable-media

  NOTE: This is NOT an upstream release and is currently maintained by 林博仁(Buo-ren, Lin), refer to the following issue tracker if you encounter any problem when using this snap:
  https://github.com/Lin-Buo-Ren/audio-recorder-snap/issues
icon: snap/gui/audio-recorder.svg

adopt-info: audio-recorder
base: core18
grade: stable
confinement: strict

plugs:
  # graphical resources access
  desktop:
  desktop-legacy:
  x11:
  unity7:

  # storage access
  home:
  removable-media:

  # audio access
  pulseaudio:

  # GNOME and Gtk runtime via content sharing
  gnome-3-28-1804:
    interface: content
    target: $SNAP/gnome-platform
    default-provider: gnome-3-28-1804
  gtk-3-themes:
    interface: content
    target: $SNAP/data-dir/themes
    default-provider: gtk-common-themes
  icon-themes:
    interface: content
    target: $SNAP/data-dir/icons
    default-provider: gtk-common-themes
  sound-themes:
    interface: content
    target: $SNAP/data-dir/sounds
    default-provider: gtk-common-themes

  # unknown
  gsettings:
  #mount-observe:
  mpris:

#slots:
  #dbus-service:
    #interface: dbus
    #name: org.gnome.API.AudioRecorderInterface
    #bus: session

parts:
  # Patches to fix other parts
  patches:
    source: snap/local/patches
    source-type: local
    plugin: dump

    organize:
      '*': patches/

    stage:
    - patches/*

    prime:
    - -*

  # CCache remote part to minimize snap development iteration
  ccache:
    source: https://github.com/ccache/ccache.git
    #source-branch: 3.5-maint
    source-depth: 1

    plugin: autotools
    # https://github.com/ccache/ccache/blob/master/doc/INSTALL.md
    build-packages:
    # For building documentation
    - asciidoc
    - xsltproc

    - gperf
    - zlib1g-dev
    override-build: |
      set \
        -o errexit \
        -o nounset
      snapcraftctl build
      install \
        --directory \
        --verbose \
        "${SNAPCRAFT_PART_INSTALL}"/bin
      for toolchain_command in \
        "${SNAPCRAFT_PART_INSTALL}"/bin/gcc \
        "${SNAPCRAFT_PART_INSTALL}"/bin/g++; do
        ln \
          --force \
          --symbolic \
          --verbose \
          ./ccache \
          "${toolchain_command}"
      done
      for gcc_release in $(seq 6 9); do
        ln \
          --force \
          --symbolic \
          --verbose \
          ./ccache \
          "${SNAPCRAFT_PART_INSTALL}"/bin/gcc-"${gcc_release}"
        ln \
          --force \
          --symbolic \
          --verbose \
          ./ccache \
          "${SNAPCRAFT_PART_INSTALL}"/bin/g++-"${gcc_release}"
      done
    prime:
    - -*

  desktop-gnome-platform:
    source: https://github.com/ubuntu/snapcraft-desktop-helpers.git
    source-depth: 1
    source-subdir: gtk

    plugin: make
    build-packages:
    - build-essential
    - libgtk-3-dev
    override-build: |
      snapcraftctl build
      mkdir -pv $SNAPCRAFT_PART_INSTALL/gnome-platform

  launchers:
    source: snap/local/launchers
    plugin: dump
    organize:
      '*': bin/

  audio-recorder:
    after:
    - ccache
    - patches

    source: lp:audio-recorder
    override-pull: |
      set -o nounset

      bzr checkout \
        --lightweight \
        lp:audio-recorder \
        .

      upstream_version="$(
        grep AC_INIT configure.ac \
          | cut --delimiter=',' --field=2 \
          | sed --regexp-extended 's/.*\[(.*)\].*$/\1/'
      )"

      upstream_dirtiness=''
      if \
        test \
        "$(
          bzr version-info \
            --custom \
            --template={clean}
        )" \
        -eq \
        0; then
        upstream_dirtiness=-dirty
      fi
      upstream_revision="$(
        bzr version-info \
          --custom \
          --template={revno}
      )"

      if test -d /root/project; then
        project_dir=/root/project
      else
        project_dir=../../..
      fi

      packaging_revision="$(
        git \
          -C "${project_dir}" \
          describe \
          --abbrev=4 \
          --always \
          --dirty=-d
      )"

      snapcraftctl set-version "${upstream_version}+rev${upstream_revision}${upstream_dirtiness}+pkg-${packaging_revision}"

    plugin: autotools
    configflags:
    - --datarootdir=/snap/audio-recorder/current/share
    build-packages:
    - gcc
    - intltool
    - libappindicator3-dev
    - libc6-dev
    - libglib2.0-dev
    - libgstreamer1.0-dev
    - libgstreamer-plugins-base1.0-dev
    - pkg-config
    stage-packages:
    - gstreamer1.0-libav
    - gstreamer1.0-plugins-base
    - gstreamer1.0-plugins-good
    - gstreamer1.0-plugins-ugly
    - gstreamer1.0-pulseaudio
    - libappindicator3-1

    # For debugging purposes
    - gstreamer1.0-tools

    organize:
      snap/audio-recorder/current/: /
    filesets:
      app-resources:
      - share/audio-recorder/*
      cleanup-debris-from-organizing:
      - -snap/*
      executables:
      - bin/*
      desktop-entries:
      - share/applications/*
      files-from-staging-packages:
      - usr/*
      glib-schemas:
      - share/glib-2.0/schemas/*
      icons:
      - share/icons/*
      localization:
      - share/locale/*
      manpages:
      - share/man/*
      pixmaps:
      - share/pixmaps/*
    stage:
    - $cleanup-debris-from-organizing

    override-stage: |
      set -eu

      snapcraftctl stage

      sed \
        --file "${SNAPCRAFT_STAGE}"/patches/postprocess-desktop-entries.sed \
        --in-place \
        "${SNAPCRAFT_STAGE}"/share/applications/*.desktop

    prime:
    # Unused gstreamer plugins
    - -usr/lib/*/gstreamer-1.0/libgstaasink.so
    - -usr/lib/*/gstreamer-1.0/libgstcacasink.so
    - -usr/lib/*/gstreamer-1.0/libgstdvd*.so
    - -usr/lib/*/gstreamer-1.0/libgsteffectv.so
    - -usr/lib/*/gstreamer-1.0/libgstjack.so
    - -usr/lib/*/gstreamer-1.0/libgstoss4.so
    - -usr/lib/*/gstreamer-1.0/libgstrealmedia.so
    - -usr/lib/*/gstreamer-1.0/libgstvideo4linux2.so

    override-prime: |
      snapcraftctl prime

      glib-compile-schemas usr/share/glib-2.0/schemas
      glib-compile-schemas share/glib-2.0/schemas

apps:
  audio-recorder:
    adapter: full
    command: bin/audio-recorder
    command-chain:
    - bin/desktop-launch
    - bin/audio-recorder-launch
    desktop: share/applications/audio-recorder.desktop
    environment:
      HOME: '$SNAP_USER_COMMON'
      GSETTINGS_SCHEMA_DIR: $SNAP/share/glib-2.0/schemas
      LD_LIBRARY_PATH: '$LD_LIBRARY_PATH:$SNAP/usr/lib/$SNAPCRAFT_ARCH_TRIPLET/pulseaudio'

    #slots:
    #- dbus-service

