name: audio-recorder
version: bzr
summary: A free audio-recorder for Linux
description: |
  This amazing program allows you to record your favourite music or audio to a file.
  It can record audio from your system's soundcard, microphones, browsers, webcams & more.
  Put simply; if it plays out of your loudspeakers you can record it.

  It has an advanced timer that can:
  * Start, stop or pause recording at a given clock time.
  * Start, stop or pause after a time period.
  * Stop when the recorded file size exceeds a limit.
  * Start recording on voice or sound (user can set the audio threshold and delay).
  * Stop or pause recording on "silence" (user can set the audio threshold and delay).

  The recording can be atomatically controlled by:
  * RhytmBox audio player.
  * Banshee audio player.
  * Amarok, VLC, Audacious and other MPRIS2 compatible players.
  * Skype. It can automatically record all your Skype calls without any user interaction.

  This program supports several audio (output) formats such as OGG audio, Flac, MP3 and WAV.

  User can also control the recorder from command line with --command <arg> option.
  See audio-recorder --help for more information.

confinement: devmode
icon: snap/gui/audio-recorder.svg

parts:
  # Patches to fix other parts
  patches:
    source: snap/patches
    source-type: local
    plugin: dump

    # DISABLED: Bug #1775582 “`organize:{ /: another-dir/ }` causes the items under host root directory to be copied in another-dir” : Bugs : Snapcraft
    # https://forum.snapcraft.io/t/organize-another-dir-causes-the-items-under-host-root-directory-to-be-copied-in-another-dir/5806
    #organize:
        #/: patches/
    override-build: |
      set -eu

      snapcraftctl build

      mkdir \
        --parents \
        "$SNAPCRAFT_PART_INSTALL"/patches
      mv \
        "$SNAPCRAFT_PART_INSTALL"/*.diff \
        "$SNAPCRAFT_PART_INSTALL"/*.patch \
        "$SNAPCRAFT_PART_INSTALL"/*.sed \
        "$SNAPCRAFT_PART_INSTALL"/patches \
        || true # Empty patches folder is allowed
    stage:
    - patches/*
    override-prime: 'true'

  # Enable ccache by setting up a dependency of this part
  # and prepend /usr/lib/ccache to the PATH colon-
  # separated array:
  #
  #   PATH=/usr/lib/ccache:"${PATH}"
  #
  # NOTE: Currently the above setup can't be applied to
  #       scriptlets as plugins doesn't honor env. var.
  #       customizations.
  #
  # or passing custom CC CXX definition to the parts'
  # configure program.
  ccache:
    plugin: nil
    build-packages:
    - ccache
    # WORKAROUND: Non-snapcraft-generated files are pulled when nil plugin is used - snapcraft - snapcraft.io
    # https://forum.snapcraft.io/t/non-snapcraft-generated-files-are-pulled-when-nil-plugin-is-used/5913
    override-pull: 'true'
    override-build: 'true'
    override-stage: |
      set -eu

      mkdir \
        --parents \
        "${SNAPCRAFT_STAGE}"/build-tools/bin
      ln \
        --force \
        --symbolic \
        "$(which ccache)" \
        "${SNAPCRAFT_STAGE}"/build-tools/bin/gcc
      ln \
        --force \
        --symbolic \
        "$(which ccache)" \
        "${SNAPCRAFT_STAGE}"/build-tools/bin/g++

  audio-recorder:
    after:
    - ccache
    - patches

    source: lp:audio-recorder

    plugin: autotools
    build-packages:
    - gcc
    - intltool
    - libappindicator3-dev
    - libc6-dev
    - libglib2.0-dev
    - libgstreamer1.0-dev
    - libgstreamer-plugins-base1.0-dev
    - libgtk-3-dev
    - pkg-config
    stage-packages:
    - libappindicator3-1
    - libglib2.0-0
    - libgstreamer1.0-0
    - libgstreamer-plugins-base1.0-0
    - libgtk-3-dev
